// Generated by gencpp from file probot_blockly/SetCurrentBlockIdRequest.msg
// DO NOT EDIT!


#ifndef PROBOT_BLOCKLY_MESSAGE_SETCURRENTBLOCKIDREQUEST_H
#define PROBOT_BLOCKLY_MESSAGE_SETCURRENTBLOCKIDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace probot_blockly
{
template <class ContainerAllocator>
struct SetCurrentBlockIdRequest_
{
  typedef SetCurrentBlockIdRequest_<ContainerAllocator> Type;

  SetCurrentBlockIdRequest_()
    : block_id()  {
    }
  SetCurrentBlockIdRequest_(const ContainerAllocator& _alloc)
    : block_id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _block_id_type;
  _block_id_type block_id;





  typedef boost::shared_ptr< ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetCurrentBlockIdRequest_

typedef ::probot_blockly::SetCurrentBlockIdRequest_<std::allocator<void> > SetCurrentBlockIdRequest;

typedef boost::shared_ptr< ::probot_blockly::SetCurrentBlockIdRequest > SetCurrentBlockIdRequestPtr;
typedef boost::shared_ptr< ::probot_blockly::SetCurrentBlockIdRequest const> SetCurrentBlockIdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator1> & lhs, const ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.block_id == rhs.block_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator1> & lhs, const ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace probot_blockly

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc6173f3373290b79e4146d870748ea6";
  }

  static const char* value(const ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc6173f3373290b7ULL;
  static const uint64_t static_value2 = 0x9e4146d870748ea6ULL;
};

template<class ContainerAllocator>
struct DataType< ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "probot_blockly/SetCurrentBlockIdRequest";
  }

  static const char* value(const ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string block_id\n"
;
  }

  static const char* value(const ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.block_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCurrentBlockIdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::probot_blockly::SetCurrentBlockIdRequest_<ContainerAllocator>& v)
  {
    s << indent << "block_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.block_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROBOT_BLOCKLY_MESSAGE_SETCURRENTBLOCKIDREQUEST_H
