// Generated by gencpp from file probot_msgs/RefreshConfigSrv.msg
// DO NOT EDIT!


#ifndef PROBOT_MSGS_MESSAGE_REFRESHCONFIGSRV_H
#define PROBOT_MSGS_MESSAGE_REFRESHCONFIGSRV_H

#include <ros/service_traits.h>


#include <probot_msgs/RefreshConfigSrvRequest.h>
#include <probot_msgs/RefreshConfigSrvResponse.h>


namespace probot_msgs
{

struct RefreshConfigSrv
{

typedef RefreshConfigSrvRequest Request;
typedef RefreshConfigSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RefreshConfigSrv
} // namespace probot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::probot_msgs::RefreshConfigSrv > {
  static const char* value()
  {
    return "5ef91ebf5713253d2dce341db84ea662";
  }

  static const char* value(const ::probot_msgs::RefreshConfigSrv&) { return value(); }
};

template<>
struct DataType< ::probot_msgs::RefreshConfigSrv > {
  static const char* value()
  {
    return "probot_msgs/RefreshConfigSrv";
  }

  static const char* value(const ::probot_msgs::RefreshConfigSrv&) { return value(); }
};


// service_traits::MD5Sum< ::probot_msgs::RefreshConfigSrvRequest> should match
// service_traits::MD5Sum< ::probot_msgs::RefreshConfigSrv >
template<>
struct MD5Sum< ::probot_msgs::RefreshConfigSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::probot_msgs::RefreshConfigSrv >::value();
  }
  static const char* value(const ::probot_msgs::RefreshConfigSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::probot_msgs::RefreshConfigSrvRequest> should match
// service_traits::DataType< ::probot_msgs::RefreshConfigSrv >
template<>
struct DataType< ::probot_msgs::RefreshConfigSrvRequest>
{
  static const char* value()
  {
    return DataType< ::probot_msgs::RefreshConfigSrv >::value();
  }
  static const char* value(const ::probot_msgs::RefreshConfigSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::probot_msgs::RefreshConfigSrvResponse> should match
// service_traits::MD5Sum< ::probot_msgs::RefreshConfigSrv >
template<>
struct MD5Sum< ::probot_msgs::RefreshConfigSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::probot_msgs::RefreshConfigSrv >::value();
  }
  static const char* value(const ::probot_msgs::RefreshConfigSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::probot_msgs::RefreshConfigSrvResponse> should match
// service_traits::DataType< ::probot_msgs::RefreshConfigSrv >
template<>
struct DataType< ::probot_msgs::RefreshConfigSrvResponse>
{
  static const char* value()
  {
    return DataType< ::probot_msgs::RefreshConfigSrv >::value();
  }
  static const char* value(const ::probot_msgs::RefreshConfigSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROBOT_MSGS_MESSAGE_REFRESHCONFIGSRV_H
