// Generated by gencpp from file probot_msgs/SFUCommandCtrlResponse.msg
// DO NOT EDIT!


#ifndef PROBOT_MSGS_MESSAGE_SFUCOMMANDCTRLRESPONSE_H
#define PROBOT_MSGS_MESSAGE_SFUCOMMANDCTRLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace probot_msgs
{
template <class ContainerAllocator>
struct SFUCommandCtrlResponse_
{
  typedef SFUCommandCtrlResponse_<ContainerAllocator> Type;

  SFUCommandCtrlResponse_()
    : ret(0)  {
    }
  SFUCommandCtrlResponse_(const ContainerAllocator& _alloc)
    : ret(0)  {
  (void)_alloc;
    }



   typedef int8_t _ret_type;
  _ret_type ret;





  typedef boost::shared_ptr< ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SFUCommandCtrlResponse_

typedef ::probot_msgs::SFUCommandCtrlResponse_<std::allocator<void> > SFUCommandCtrlResponse;

typedef boost::shared_ptr< ::probot_msgs::SFUCommandCtrlResponse > SFUCommandCtrlResponsePtr;
typedef boost::shared_ptr< ::probot_msgs::SFUCommandCtrlResponse const> SFUCommandCtrlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator1> & lhs, const ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ret == rhs.ret;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator1> & lhs, const ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace probot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba0ef05866f4fc5d7e82544d27e5cfbc";
  }

  static const char* value(const ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba0ef05866f4fc5dULL;
  static const uint64_t static_value2 = 0x7e82544d27e5cfbcULL;
};

template<class ContainerAllocator>
struct DataType< ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "probot_msgs/SFUCommandCtrlResponse";
  }

  static const char* value(const ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 ret\n"
;
  }

  static const char* value(const ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SFUCommandCtrlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::probot_msgs::SFUCommandCtrlResponse_<ContainerAllocator>& v)
  {
    s << indent << "ret: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ret);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROBOT_MSGS_MESSAGE_SFUCOMMANDCTRLRESPONSE_H
